dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: ubidy-agencyapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.230
- name: ubidy-agencycandidatecenterapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.72
- name: ubidy-agencyemailpreferenceapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.113
- name: ubidy-agencyengagementapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.142
- name: ubidy-agencyengagementboardsapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.44
- name: ubidy-agencynotificationapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.34
- name: ubidy-applicationapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.47
- name: ubidy-applicationlookupapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.153
- name: ubidy-commentssocketapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.32
- name: ubidy-documentapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.33
- name: ubidy-employerapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 2.1.68
- name: ubidy-employercandidatecenterapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.21
- name: ubidy-employeremailpreferenceapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.86
- name: ubidy-employerengagementapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.242
- name: ubidy-employerengagementboardsapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.46
- name: ubidy-employernotificationapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.47
- name: ubidy-messagequeueapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.50
- name: ubidy-messengerapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.28
- name: ubidy-opportunitiesapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.102
