dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: ubidy-agencyapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.263
- name: ubidy-agencycandidatecenterapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.89
- name: ubidy-agencyemailpreferenceapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.121
- name: ubidy-agencyengagementapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.187
- name: ubidy-agencyengagementboardsapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.103
- name: ubidy-agencynotificationapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.39
- name: ubidy-applicationapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.55
- name: ubidy-applicationlookupapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.159
- name: ubidy-backofficeapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.16
- name: ubidy-commentssocketapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.88
- name: ubidy-documentapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.39
- name: ubidy-employerapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 2.1.93
- name: ubidy-employercandidatecenterapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.35
- name: ubidy-employeremailpreferenceapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.94
- name: ubidy-employerengagementapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.371
- name: ubidy-employerengagementboardsapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.62
- name: ubidy-employernotificationapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.64
- name: ubidy-messagequeueapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.57
- name: ubidy-messengerapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.36
- name: ubidy-opportunitiesapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.113
