dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: ubidy-agencyapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.262
- name: ubidy-agencycandidatecenterapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.83
- name: ubidy-agencyemailpreferenceapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.113
- name: ubidy-agencyengagementapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.186
- name: ubidy-agencyengagementboardsapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.98
- name: ubidy-agencynotificationapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.34
- name: ubidy-applicationapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.54
- name: ubidy-applicationlookupapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.158
- name: ubidy-backofficeapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.16
- name: ubidy-commentssocketapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.85
- name: ubidy-documentapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.37
- name: ubidy-employerapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 2.1.90
- name: ubidy-employercandidatecenterapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.30
- name: ubidy-employeremailpreferenceapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.91
- name: ubidy-employerengagementapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.369
- name: ubidy-employerengagementboardsapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.56
- name: ubidy-employernotificationapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.62
- name: ubidy-messagequeueapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.55
- name: ubidy-messengerapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.32
- name: ubidy-opportunitiesapi
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.110
